server:
  port: 8083
spring:
  application:
    name: search-server
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.0.105:9300
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 192.168.0.105
    username: ly
    password: leyou
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10 #拉取时间
  instance:
    lease-renewal-interval-in-seconds: 5  #心跳时间
    lease-expiration-duration-in-seconds: 15 #失效时间