server:
  port: 8087
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql:///wb?serverTimezone=UTC
    username: root
    password: root
  rabbitmq:
    host: 192.168.0.105
    username: ly
    password: leyou
    virtual-host: /leyou
    template:
      exchange: LEYOU.ITEM.EXCHANGE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 #心跳时间
    lease-expiration-duration-in-seconds: 15 #过期时间
mybatis:
  type-aliases-package: com.leyou.item.pojo
