server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.0.105
    username: ly
    password: leyou
    virtual-host: /leyou
leyou:
  sms:
    accessKeyId: # 你自己的accessKeyId
    accessKeySecret:  # 你自己的AccessKeySecret
    signName: 乐游网吧 # 签名名称
    verifyCodeTemplate: SMS_188991470 # 模板名称