server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.0.105
    username: ly
    password: leyou
    virtual-host: /leyou
leyou:
  sms:
    accessKeyId: LTAI4G64W3rjjbnh3Asu61WH # 你自己的accessKeyId
    accessKeySecret: brCpYgdV4y1SpgIr10v62Kkjjx89CF # 你自己的AccessKeySecret
    signName: 乐游网吧 # 签名名称
    verifyCodeTemplate: SMS_188991470 # 模板名称