server:
  port: 8089
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.0.105
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
leyou:
  jwt:
    pubKeyPath: G:\study\leyou\tool\JwtandRSA\rsa.pub # 公钥地址
    cookieName: LY_TOKEN